import { defineDeck } from "@pptx/core";

/**
 * Mock data — a tour of every motion technique the pipeline exports as native
 * PowerPoint: Morph (same object resized/moved/recolored across slides),
 * camera push-in, motion paths, looping emphasis, enter→emphasize→exit
 * lifecycles, "On click of" triggers and dim-after reveals. Figures invented.
 */
export const motionShowcase = defineDeck({
  id: "motion-showcase",
  title: "Motion Showcase",
  lang: "en-US",
  author: "Design Systems",
  transition: { effect: "fade", duration: 0.4 },
  slides: [
    {
      id: "cover",
      layout: "cover",
      title: "Motion Showcase",
      subtitle: "Morph, motion paths, emphasis and triggers — all native PowerPoint",
      presenter: "Design Systems",
      date: "Play in Slide Show (F5)",
    },

    // ── Morph: one object, two slides ─────────────────────────────────────
    {
      id: "morph-start",
      layout: "stage",
      title: "Morph: same object, new size and place",
      objects: [
        {
          id: "orb",
          shape: "circle",
          x: 140,
          y: 300,
          width: 160,
          height: 160,
          fill: "primary",
          text: "Q3",
          fontSize: 36,
          morph: "orb",
        },
        {
          id: "hint",
          shape: "rounded",
          x: 360,
          y: 330,
          width: 560,
          height: 100,
          fill: "surface",
          textColor: "text",
          text: "This circle is one object across two slides",
          animation: { effect: "entrance_fade", duration: 0.6 },
        },
      ],
      notes: "Advance: the orb morphs — it moves, grows and changes color in one motion.",
    },
    {
      id: "morph-end",
      layout: "stage",
      title: "Morph: same object, new size and place",
      // Paired objects force a Morph transition; the slide may tune it.
      transition: { effect: "morph", duration: 1.2 },
      objects: [
        {
          id: "orb",
          shape: "circle",
          x: 720,
          y: 150,
          width: 440,
          height: 440,
          fill: "accent",
          text: "Q3 revenue $48.2M",
          fontSize: 44,
          morph: "orb",
        },
        {
          id: "detail",
          shape: "rounded",
          x: 80,
          y: 300,
          width: 560,
          height: 140,
          fill: "surface",
          textColor: "text",
          text: "Morph interpolated position, size and fill",
          animation: { effect: "entrance_rise_up", duration: 0.5, delay: 0.2 },
        },
      ],
    },

    // ── Camera push-in: grid → one card fills the frame ───────────────────
    {
      id: "push-grid",
      layout: "stage",
      title: "Camera push-in",
      objects: [
        {
          id: "north",
          shape: "rounded",
          x: 80,
          y: 220,
          width: 340,
          height: 260,
          fill: "primary",
          text: "North America",
          morph: "card-north",
          animation: { effect: "entrance_zoom", duration: 0.4 },
        },
        {
          id: "europe",
          shape: "rounded",
          x: 470,
          y: 220,
          width: 340,
          height: 260,
          fill: "accent",
          text: "Europe",
          morph: "card-europe",
          animation: { effect: "entrance_zoom", duration: 0.4 },
        },
        {
          id: "apac",
          shape: "rounded",
          x: 860,
          y: 220,
          width: 340,
          height: 260,
          fill: "positive",
          text: "APAC",
          morph: "card-apac",
          animation: { effect: "entrance_zoom", duration: 0.4 },
        },
      ],
      caption: "Next slide keeps only Europe — Morph zooms into it, the others fade away.",
    },
    {
      id: "push-focus",
      layout: "stage",
      title: "Camera push-in",
      objects: [
        {
          id: "europe",
          shape: "rounded",
          x: 80,
          y: 140,
          width: 780,
          height: 480,
          fill: "accent",
          text: "Europe · $13.9M · +22% YoY",
          fontSize: 52,
          morph: "card-europe",
        },
        {
          // Morph-paired objects can be triggers: click the big card for the note.
          id: "europe-note",
          shape: "rounded",
          x: 900,
          y: 140,
          width: 300,
          height: 480,
          fill: "surface",
          textColor: "text",
          text: "Driver: Atlas Picker rollouts in 14 EU warehouses",
          fontSize: 28,
          animation: { effect: "entrance_zoom", duration: 0.4, triggerShape: "europe" },
        },
      ],
      caption: "In Slide Show, click the Europe card to reveal the note.",
    },
    {
      // Pull back out: same keys as push-grid, so Morph shrinks Europe into the
      // grid and the unpaired cards fade in. No entrance animations here — Morph
      // already brings them in.
      id: "pull-grid",
      layout: "stage",
      title: "Camera pull-out",
      objects: [
        {
          id: "north",
          shape: "rounded",
          x: 80,
          y: 220,
          width: 340,
          height: 260,
          fill: "primary",
          text: "North America",
          morph: "card-north",
        },
        {
          id: "europe",
          shape: "rounded",
          x: 470,
          y: 220,
          width: 340,
          height: 260,
          fill: "accent",
          text: "Europe",
          morph: "card-europe",
        },
        {
          id: "apac",
          shape: "rounded",
          x: 860,
          y: 220,
          width: 340,
          height: 260,
          fill: "positive",
          text: "APAC",
          morph: "card-apac",
        },
      ],
    },

    // ── Morph re-sort: bars swap rank and resize ──────────────────────────
    {
      id: "rank-before",
      layout: "stage",
      title: "Morph re-sort: regional ranking",
      objects: [
        {
          id: "europe",
          shape: "rounded",
          x: 300,
          y: 180,
          width: 613,
          height: 100,
          fill: "accent",
          text: "Europe $16.0M",
          fontSize: 28,
          morph: "rank-europe",
        },
        {
          id: "north",
          shape: "rounded",
          x: 300,
          y: 330,
          width: 582,
          height: 100,
          fill: "primary",
          text: "North America $15.2M",
          fontSize: 28,
          morph: "rank-north",
        },
        {
          id: "apac",
          shape: "rounded",
          x: 300,
          y: 480,
          width: 233,
          height: 100,
          fill: "positive",
          text: "APAC $6.1M",
          fontSize: 28,
          morph: "rank-apac",
        },
      ],
      caption: "Q2 2026: Europe leads. Advance: bars re-sort and resize to Q3 values in one Morph.",
    },
    {
      id: "rank-after",
      layout: "stage",
      title: "Morph re-sort: regional ranking",
      objects: [
        {
          id: "north",
          shape: "rounded",
          x: 300,
          y: 180,
          width: 820,
          height: 100,
          fill: "primary",
          text: "North America $21.4M",
          fontSize: 28,
          morph: "rank-north",
        },
        {
          id: "europe",
          shape: "rounded",
          x: 300,
          y: 330,
          width: 532,
          height: 100,
          fill: "accent",
          text: "Europe $13.9M",
          fontSize: 28,
          morph: "rank-europe",
        },
        {
          id: "apac",
          shape: "rounded",
          x: 300,
          y: 480,
          width: 329,
          height: 100,
          fill: "positive",
          text: "APAC $8.6M",
          fontSize: 28,
          morph: "rank-apac",
        },
      ],
      caption: "Q3 2026: North America overtakes. Each bar is paired by its morph key.",
    },

    // ── Motion paths and looping emphasis ─────────────────────────────────
    {
      id: "paths-emphasis",
      layout: "stage",
      title: "Motion paths & emphasis",
      objects: [
        {
          id: "launch",
          shape: "pill",
          x: 80,
          y: 170,
          width: 240,
          height: 90,
          fill: "primary",
          text: "Launch",
          // Relative motion path (the preset carries its own easing).
          animation: { effect: "path_right", options: { relative: true }, duration: 2 },
        },
        {
          id: "badge",
          shape: "circle",
          x: 100,
          y: 360,
          width: 200,
          height: 200,
          fill: "accent",
          text: "NEW",
          fontSize: 40,
          // Enter, then pulse twice (grow and shrink back).
          animation: [
            { effect: "entrance_zoom", duration: 0.4 },
            {
              effect: "emphasis_grow_shrink",
              options: { size: 115 },
              duration: 0.5,
              autoReverse: true,
              repeatCount: 2,
            },
          ],
        },
        {
          id: "sync",
          shape: "rounded",
          x: 440,
          y: 380,
          width: 180,
          height: 180,
          fill: "positive",
          text: "Sync",
          animation: {
            effect: "emphasis_spin",
            options: { amount: 360 },
            duration: 1.2,
            repeatCount: 2,
          },
        },
        {
          id: "alert",
          shape: "rounded",
          x: 760,
          y: 400,
          width: 420,
          height: 140,
          fill: "negative",
          text: "Heads up!",
          fontSize: 36,
          animation: [
            { effect: "entrance_fade", duration: 0.3 },
            { effect: "emphasis_teeter", duration: 0.5, repeatCount: 2 },
          ],
        },
      ],
    },

    // ── Lifecycle: enter → emphasize → exit, then the next state ──────────
    {
      id: "lifecycle",
      layout: "stage",
      title: "Enter, emphasize, exit",
      objects: [
        {
          id: "saving",
          shape: "pill",
          x: 390,
          y: 230,
          width: 500,
          height: 100,
          fill: "text",
          textColor: "background",
          text: "Saving draft…",
          animation: [
            { effect: "entrance_fly", options: { direction: "up" }, duration: 0.5 },
            { effect: "emphasis_teeter", duration: 0.6 },
            { effect: "exit_fade", duration: 0.4, delay: 0.8 },
          ],
        },
        {
          id: "saved",
          shape: "pill",
          x: 390,
          y: 420,
          width: 500,
          height: 100,
          fill: "positive",
          text: "Saved",
          animation: { effect: "entrance_zoom", duration: 0.4, bounceEnd: 0.3 },
        },
      ],
    },

    // ── Interactive trigger: click one object to reveal another ───────────
    {
      id: "click-reveal",
      layout: "stage",
      title: "Click to reveal (On click of)",
      objects: [
        {
          id: "question",
          shape: "rounded",
          x: 80,
          y: 180,
          width: 520,
          height: 320,
          fill: "primary",
          text: "What drove Q3 growth? Click me",
          fontSize: 36,
        },
        {
          id: "answer",
          shape: "rounded",
          x: 680,
          y: 180,
          width: 520,
          height: 320,
          fill: "surface",
          textColor: "text",
          text: "Atlas Picker upgrades in EU warehouses",
          fontSize: 32,
          animation: {
            effect: "entrance_wipe",
            options: { direction: "right" },
            duration: 0.6,
            triggerShape: "question",
          },
        },
      ],
      caption: "In Slide Show, click the blue card — the answer only appears on that click.",
    },

    // ── Presenter-paced build with dim-after on a regular layout ──────────
    {
      id: "recap",
      layout: "agenda",
      title: "Recap",
      items: ["Morph", "Camera push-in and pull-out", "Motion paths", "Lifecycles", "Triggers"],
      // Overrides on a built-in layout: click per item, dim the previous one.
      animations: Object.fromEntries(
        [0, 1, 2, 3, 4].map((i) => [
          `item-${i}`,
          {
            effect: "entrance_fly",
            options: { direction: "right" },
            duration: 0.4,
            trigger: "on-click",
            afterEffect: { type: "dim", color: "#94A3B8" },
          },
        ]),
      ),
    },
    {
      id: "closing",
      layout: "closing",
      title: "All native, all editable",
      subtitle: "Open the Animation Pane to tweak any of it",
      contact: "motion@showcase.example",
      transition: { effect: "vortex", duration: 1.5 },
    },
  ],
});
