// GENERATED by scripts/sync-motion-presets.py from vendor/ppt-master — do not edit.

/** Native PowerPoint object animation presets (entrance/emphasis/path/exit). */
export type AnimationEffect =
  | "entrance_appear"
  | "entrance_fly"
  | "entrance_blinds"
  | "entrance_box"
  | "entrance_checkerboard"
  | "entrance_circle"
  | "entrance_crawl"
  | "entrance_diamond"
  | "entrance_dissolve"
  | "entrance_fade"
  | "entrance_flash_once"
  | "entrance_peek"
  | "entrance_plus"
  | "entrance_random_bars"
  | "entrance_spiral"
  | "entrance_split"
  | "entrance_stretch"
  | "entrance_strips"
  | "entrance_swivel"
  | "entrance_wedge"
  | "entrance_wheel"
  | "entrance_wipe"
  | "entrance_zoom"
  | "entrance_random_effects"
  | "entrance_boomerang"
  | "entrance_bounce"
  | "entrance_color_reveal"
  | "entrance_credits"
  | "entrance_ease_in"
  | "entrance_float"
  | "entrance_grow_and_turn"
  | "entrance_light_speed"
  | "entrance_pinwheel"
  | "entrance_rise_up"
  | "entrance_swish"
  | "entrance_thin_line"
  | "entrance_unfold"
  | "entrance_whip"
  | "entrance_ascend"
  | "entrance_center_revolve"
  | "entrance_faded_swivel"
  | "entrance_descend"
  | "entrance_sling"
  | "entrance_spinner"
  | "entrance_stretchy"
  | "entrance_zip"
  | "entrance_arc_up"
  | "entrance_faded_zoom"
  | "entrance_glide"
  | "entrance_expand"
  | "entrance_flip"
  | "entrance_fold"
  | "entrance_3d_arrive"
  | "emphasis_shimmer"
  | "emphasis_change_fill_color"
  | "emphasis_change_font"
  | "emphasis_change_font_color"
  | "emphasis_change_font_size"
  | "emphasis_change_font_style"
  | "emphasis_grow_shrink"
  | "emphasis_change_line_color"
  | "emphasis_spin"
  | "emphasis_transparency"
  | "emphasis_bold_flash"
  | "emphasis_blast"
  | "emphasis_bold_reveal"
  | "emphasis_brush_on_color"
  | "emphasis_brush_on_underline"
  | "emphasis_color_blend"
  | "emphasis_color_wave"
  | "emphasis_complementary_color"
  | "emphasis_complementary_color2"
  | "emphasis_contrasting_color"
  | "emphasis_darken"
  | "emphasis_desaturate"
  | "emphasis_flash_bulb"
  | "emphasis_flicker"
  | "emphasis_grow_with_color"
  | "emphasis_lighten"
  | "emphasis_style_emphasis"
  | "emphasis_teeter"
  | "emphasis_vertical_grow"
  | "emphasis_wave"
  | "emphasis_3d_turntable"
  | "emphasis_3d_swing"
  | "emphasis_3d_jump_and_turn"
  | "path_circle"
  | "path_right_triangle"
  | "path_diamond"
  | "path_hexagon"
  | "path_5_point_star"
  | "path_crescent_moon"
  | "path_square"
  | "path_trapezoid"
  | "path_heart"
  | "path_octagon"
  | "path_6_point_star"
  | "path_football"
  | "path_equal_triangle"
  | "path_parallelogram"
  | "path_pentagon"
  | "path_4_point_star"
  | "path_8_point_star"
  | "path_teardrop"
  | "path_pointy_star"
  | "path_curved_square"
  | "path_curved_x"
  | "path_vertical_figure8"
  | "path_curvy_star"
  | "path_loopde_loop"
  | "path_buzzsaw"
  | "path_horizontal_figure8"
  | "path_peanut"
  | "path_figure8_four"
  | "path_neutron"
  | "path_swoosh"
  | "path_bean"
  | "path_plus"
  | "path_inverted_triangle"
  | "path_inverted_square"
  | "path_left"
  | "path_turn_right"
  | "path_arc_down"
  | "path_zigzag"
  | "path_s_curve2"
  | "path_sine_wave"
  | "path_bounce_left"
  | "path_down"
  | "path_turn_up"
  | "path_arc_up"
  | "path_heartbeat"
  | "path_spiral_right"
  | "path_wave"
  | "path_curvy_left"
  | "path_diagonal_down_right"
  | "path_turn_down"
  | "path_arc_left"
  | "path_funnel"
  | "path_spring"
  | "path_bounce_right"
  | "path_spiral_left"
  | "path_diagonal_up_right"
  | "path_turn_up_right"
  | "path_arc_right"
  | "path_s_curve1"
  | "path_decaying_wave"
  | "path_curvy_right"
  | "path_stairs_down"
  | "path_up"
  | "path_right"
  | "exit_appear"
  | "exit_fly"
  | "exit_blinds"
  | "exit_box"
  | "exit_checkerboard"
  | "exit_circle"
  | "exit_crawl"
  | "exit_diamond"
  | "exit_dissolve"
  | "exit_fade"
  | "exit_flash_once"
  | "exit_peek"
  | "exit_plus"
  | "exit_random_bars"
  | "exit_spiral"
  | "exit_split"
  | "exit_stretch"
  | "exit_strips"
  | "exit_swivel"
  | "exit_wedge"
  | "exit_wheel"
  | "exit_wipe"
  | "exit_zoom"
  | "exit_random_effects"
  | "exit_boomerang"
  | "exit_bounce"
  | "exit_color_reveal"
  | "exit_credits"
  | "exit_ease_in"
  | "exit_float"
  | "exit_grow_and_turn"
  | "exit_light_speed"
  | "exit_pinwheel"
  | "exit_rise_up"
  | "exit_swish"
  | "exit_thin_line"
  | "exit_unfold"
  | "exit_whip"
  | "exit_ascend"
  | "exit_center_revolve"
  | "exit_faded_swivel"
  | "exit_descend"
  | "exit_sling"
  | "exit_spinner"
  | "exit_stretchy"
  | "exit_zip"
  | "exit_arc_up"
  | "exit_faded_zoom"
  | "exit_glide"
  | "exit_expand"
  | "exit_flip"
  | "exit_fold"
  | "exit_3d_arrive";

/** Native PowerPoint slide transitions. */
export type TransitionEffect =
  | "morph"
  | "fade"
  | "push"
  | "wipe"
  | "split"
  | "reveal"
  | "cut"
  | "random_bars"
  | "shape"
  | "uncover"
  | "cover"
  | "flash"
  | "fall_over"
  | "drape"
  | "curtains"
  | "wind"
  | "prestige"
  | "fracture"
  | "crush"
  | "peel_off"
  | "page_curl"
  | "airplane"
  | "origami"
  | "dissolve"
  | "checkerboard"
  | "blinds"
  | "clock"
  | "ripple"
  | "honeycomb"
  | "glitter"
  | "vortex"
  | "shred"
  | "switch"
  | "flip"
  | "gallery"
  | "cube"
  | "doors"
  | "box"
  | "comb"
  | "zoom"
  | "random"
  | "pan"
  | "ferris_wheel"
  | "conveyor"
  | "rotate"
  | "window"
  | "orbit"
  | "fly_through";

/** PowerPoint Start mode for an animation row. */
export type AnimationTrigger = "on-click" | "with-previous" | "after-previous";

export const ANIMATION_EFFECTS: readonly AnimationEffect[] = [
  "entrance_appear",
  "entrance_fly",
  "entrance_blinds",
  "entrance_box",
  "entrance_checkerboard",
  "entrance_circle",
  "entrance_crawl",
  "entrance_diamond",
  "entrance_dissolve",
  "entrance_fade",
  "entrance_flash_once",
  "entrance_peek",
  "entrance_plus",
  "entrance_random_bars",
  "entrance_spiral",
  "entrance_split",
  "entrance_stretch",
  "entrance_strips",
  "entrance_swivel",
  "entrance_wedge",
  "entrance_wheel",
  "entrance_wipe",
  "entrance_zoom",
  "entrance_random_effects",
  "entrance_boomerang",
  "entrance_bounce",
  "entrance_color_reveal",
  "entrance_credits",
  "entrance_ease_in",
  "entrance_float",
  "entrance_grow_and_turn",
  "entrance_light_speed",
  "entrance_pinwheel",
  "entrance_rise_up",
  "entrance_swish",
  "entrance_thin_line",
  "entrance_unfold",
  "entrance_whip",
  "entrance_ascend",
  "entrance_center_revolve",
  "entrance_faded_swivel",
  "entrance_descend",
  "entrance_sling",
  "entrance_spinner",
  "entrance_stretchy",
  "entrance_zip",
  "entrance_arc_up",
  "entrance_faded_zoom",
  "entrance_glide",
  "entrance_expand",
  "entrance_flip",
  "entrance_fold",
  "entrance_3d_arrive",
  "emphasis_shimmer",
  "emphasis_change_fill_color",
  "emphasis_change_font",
  "emphasis_change_font_color",
  "emphasis_change_font_size",
  "emphasis_change_font_style",
  "emphasis_grow_shrink",
  "emphasis_change_line_color",
  "emphasis_spin",
  "emphasis_transparency",
  "emphasis_bold_flash",
  "emphasis_blast",
  "emphasis_bold_reveal",
  "emphasis_brush_on_color",
  "emphasis_brush_on_underline",
  "emphasis_color_blend",
  "emphasis_color_wave",
  "emphasis_complementary_color",
  "emphasis_complementary_color2",
  "emphasis_contrasting_color",
  "emphasis_darken",
  "emphasis_desaturate",
  "emphasis_flash_bulb",
  "emphasis_flicker",
  "emphasis_grow_with_color",
  "emphasis_lighten",
  "emphasis_style_emphasis",
  "emphasis_teeter",
  "emphasis_vertical_grow",
  "emphasis_wave",
  "emphasis_3d_turntable",
  "emphasis_3d_swing",
  "emphasis_3d_jump_and_turn",
  "path_circle",
  "path_right_triangle",
  "path_diamond",
  "path_hexagon",
  "path_5_point_star",
  "path_crescent_moon",
  "path_square",
  "path_trapezoid",
  "path_heart",
  "path_octagon",
  "path_6_point_star",
  "path_football",
  "path_equal_triangle",
  "path_parallelogram",
  "path_pentagon",
  "path_4_point_star",
  "path_8_point_star",
  "path_teardrop",
  "path_pointy_star",
  "path_curved_square",
  "path_curved_x",
  "path_vertical_figure8",
  "path_curvy_star",
  "path_loopde_loop",
  "path_buzzsaw",
  "path_horizontal_figure8",
  "path_peanut",
  "path_figure8_four",
  "path_neutron",
  "path_swoosh",
  "path_bean",
  "path_plus",
  "path_inverted_triangle",
  "path_inverted_square",
  "path_left",
  "path_turn_right",
  "path_arc_down",
  "path_zigzag",
  "path_s_curve2",
  "path_sine_wave",
  "path_bounce_left",
  "path_down",
  "path_turn_up",
  "path_arc_up",
  "path_heartbeat",
  "path_spiral_right",
  "path_wave",
  "path_curvy_left",
  "path_diagonal_down_right",
  "path_turn_down",
  "path_arc_left",
  "path_funnel",
  "path_spring",
  "path_bounce_right",
  "path_spiral_left",
  "path_diagonal_up_right",
  "path_turn_up_right",
  "path_arc_right",
  "path_s_curve1",
  "path_decaying_wave",
  "path_curvy_right",
  "path_stairs_down",
  "path_up",
  "path_right",
  "exit_appear",
  "exit_fly",
  "exit_blinds",
  "exit_box",
  "exit_checkerboard",
  "exit_circle",
  "exit_crawl",
  "exit_diamond",
  "exit_dissolve",
  "exit_fade",
  "exit_flash_once",
  "exit_peek",
  "exit_plus",
  "exit_random_bars",
  "exit_spiral",
  "exit_split",
  "exit_stretch",
  "exit_strips",
  "exit_swivel",
  "exit_wedge",
  "exit_wheel",
  "exit_wipe",
  "exit_zoom",
  "exit_random_effects",
  "exit_boomerang",
  "exit_bounce",
  "exit_color_reveal",
  "exit_credits",
  "exit_ease_in",
  "exit_float",
  "exit_grow_and_turn",
  "exit_light_speed",
  "exit_pinwheel",
  "exit_rise_up",
  "exit_swish",
  "exit_thin_line",
  "exit_unfold",
  "exit_whip",
  "exit_ascend",
  "exit_center_revolve",
  "exit_faded_swivel",
  "exit_descend",
  "exit_sling",
  "exit_spinner",
  "exit_stretchy",
  "exit_zip",
  "exit_arc_up",
  "exit_faded_zoom",
  "exit_glide",
  "exit_expand",
  "exit_flip",
  "exit_fold",
  "exit_3d_arrive",
];

export const TRANSITION_EFFECTS: readonly TransitionEffect[] = [
  "morph",
  "fade",
  "push",
  "wipe",
  "split",
  "reveal",
  "cut",
  "random_bars",
  "shape",
  "uncover",
  "cover",
  "flash",
  "fall_over",
  "drape",
  "curtains",
  "wind",
  "prestige",
  "fracture",
  "crush",
  "peel_off",
  "page_curl",
  "airplane",
  "origami",
  "dissolve",
  "checkerboard",
  "blinds",
  "clock",
  "ripple",
  "honeycomb",
  "glitter",
  "vortex",
  "shred",
  "switch",
  "flip",
  "gallery",
  "cube",
  "doors",
  "box",
  "comb",
  "zoom",
  "random",
  "pan",
  "ferris_wheel",
  "conveyor",
  "rotate",
  "window",
  "orbit",
  "fly_through",
];
