"""Generate motion artifacts from the vendored ppt-master registry.

Outputs (never hand-edit them; re-run after bumping vendor/ppt-master):
  packages/core/src/motion-presets.generated.ts
      TypeScript unions for every effect / transition / trigger the exporter accepts.
  .claude/skills/pptx-object-animations/references/effect-catalog.md
  .claude/skills/pptx-transitions/references/transition-catalog.md
      Agent-facing catalogs: PowerPoint names, default durations, exact options.

Run:  bun run sync:motion
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / "vendor/ppt-master/skills/ppt-master/scripts"
OUT = ROOT / "packages/core/src/motion-presets.generated.ts"
SKILLS = ROOT / ".claude/skills"
EFFECT_CATALOG = SKILLS / "pptx-object-animations/references/effect-catalog.md"
TRANSITION_CATALOG = SKILLS / "pptx-transitions/references/transition-catalog.md"

sys.path.insert(0, str(SCRIPTS))
import pptx_animations  # noqa: E402


def union(name: str, doc: str, keys: tuple[str, ...]) -> str:
    body = "\n".join(f'  | "{key}"' for key in keys)
    return f"/** {doc} */\nexport type {name} =\n{body};\n"


def const(name: str, keys: tuple[str, ...], type_name: str) -> str:
    body = "\n".join(f'  "{key}",' for key in keys)
    return f"export const {name}: readonly {type_name}[] = [\n{body}\n];\n"


def fmt_options(options: dict) -> str:
    """Render an effect_options spec as `name: a|b|c (default x)`."""
    if not options:
        return "—"
    parts = []
    for name, spec in options.items():
        values = spec.get("values")
        if isinstance(values, dict):
            values = list(values)
        # " / " not "|": a pipe would split the Markdown table cell.
        kind = " / ".join(f"`{v}`" for v in values) if values else spec.get("type", "?")
        default = spec.get("default")
        if isinstance(default, bool):
            default = str(default).lower()
        parts.append(f"`{name}`: {kind}" + (f" (default `{default}`)" if default is not None else ""))
    return "<br>".join(parts)


HEADER = (
    "<!-- GENERATED by scripts/sync-motion-presets.py from vendor/ppt-master — do not edit. -->\n\n"
)


def write_effect_catalog() -> None:
    lines = [
        HEADER,
        "# Object animation effect catalog\n\n",
        "Every key accepted in `AnimationStep.effect`, grouped by PowerPoint category, with the\n",
        "PowerPoint UI name, the preset's default duration and its exact `options`.\n",
        "Use with [`../SKILL.md`](../SKILL.md). Live details for one effect:\n",
        "`.venv/bin/python vendor/ppt-master/skills/ppt-master/scripts/pptx_animations.py --describe <key>`.\n\n",
        "Contents: " + " · ".join(f"[{c}](#{c})" for c in pptx_animations.ANIMATION_CATEGORIES) + "\n",
    ]
    for category in pptx_animations.ANIMATION_CATEGORIES:
        keys = [k for k, v in pptx_animations.NATIVE_ANIMATIONS.items() if v.get("category") == category]
        lines.append(f"\n## {category}\n\n{len(keys)} effects.\n\n")
        lines.append("| key | PowerPoint name | default s | options |\n|---|---|---|---|\n")
        for key in keys:
            spec = pptx_animations.NATIVE_ANIMATIONS[key]
            described = pptx_animations.describe_animation_effect(key)
            options = fmt_options(described.get("effect_options") or {})
            ms = spec.get("defaultDurationMs")
            seconds = f"{ms / 1000:g}" if ms else "instant"
            lines.append(f"| `{key}` | {spec.get('name', '')} | {seconds} | {options} |\n")
    EFFECT_CATALOG.parent.mkdir(parents=True, exist_ok=True)
    EFFECT_CATALOG.write_text("".join(lines), encoding="utf-8")


def write_transition_catalog() -> None:
    titles = {
        "subtle": "Subtle — everyday continuity",
        "exciting": "Exciting — rare, deliberate beats",
        "dynamic_content": "Dynamic content — background stays, content moves",
    }
    lines = [
        HEADER,
        "# Slide transition catalog\n\n",
        "Every key accepted in `Transition.effect` (plus `none`), grouped by PowerPoint's own\n",
        "Transitions-tab categories, with exact `options`. Use with [`../SKILL.md`](../SKILL.md).\n",
        "Live details: `pptx_animations.py --describe-transition <key>`.\n",
    ]
    for category in pptx_animations.TRANSITION_CATEGORIES:
        keys = [k for k, v in pptx_animations.NATIVE_TRANSITIONS.items() if v.get("category") == category]
        lines.append(f"\n## {titles.get(category, category)}\n\n")
        lines.append("| key | PowerPoint name | options |\n|---|---|---|\n")
        for key in keys:
            spec = pptx_animations.NATIVE_TRANSITIONS[key]
            described = pptx_animations.describe_transition_effect(key)
            options = fmt_options(described.get("effect_options") or {})
            lines.append(f"| `{key}` | {spec.get('name', '')} | {options} |\n")
    TRANSITION_CATALOG.parent.mkdir(parents=True, exist_ok=True)
    TRANSITION_CATALOG.write_text("".join(lines), encoding="utf-8")


def main() -> None:
    animations = tuple(pptx_animations.NATIVE_ANIMATION_KEYS)
    transitions = tuple(pptx_animations.NATIVE_TRANSITION_KEYS)
    triggers = tuple(pptx_animations.ANIMATION_TRIGGERS)
    parts = [
        "// GENERATED by scripts/sync-motion-presets.py from vendor/ppt-master — do not edit.\n",
        union("AnimationEffect", "Native PowerPoint object animation presets (entrance/emphasis/path/exit).", animations),
        union("TransitionEffect", "Native PowerPoint slide transitions.", transitions),
        union("AnimationTrigger", "PowerPoint Start mode for an animation row.", triggers),
        const("ANIMATION_EFFECTS", animations, "AnimationEffect"),
        const("TRANSITION_EFFECTS", transitions, "TransitionEffect"),
    ]
    OUT.write_text("\n".join(parts), encoding="utf-8")
    write_effect_catalog()
    write_transition_catalog()
    print(f"wrote {OUT.relative_to(ROOT)} ({len(animations)} animations, {len(transitions)} transitions)")
    print(f"wrote {EFFECT_CATALOG.relative_to(ROOT)}")
    print(f"wrote {TRANSITION_CATALOG.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
